version: '3'

# run tests:  cd ci/unit; docker-compose up --build --force-recreate
# manual:  cd ci/unit; docker-compose run logstash bash
services:

  logstash:
    build:
      context: ../
      dockerfile: .ci/Dockerfile
      args:
        - ELASTIC_STACK_VERSION=$ELASTIC_STACK_VERSION
    command: .ci/run.sh
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      LOGSTASH_SOURCE: 1
    tty: true